version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  commit-message:
    prefix: "fix"
    prefix-development: "build"
    include: "scope"
  open-pull-requests-limit: 10
  reviewers:
  - raimondb
